FROM ubuntu:latest
RUN apt-get update && apt-get -y update 
RUN apt-get install -y git
RUN apt-get install -y build-essential python3.6 python3-pip python3-dev
RUN pip3 -q install pip --upgrade

RUN pip install git+git://github.com/lux-org/lux-widget.git
RUN pip install git+git://github.com/lux-org/lux.git
RUN jupyter nbextension install --py luxwidget
RUN jupyter nbextension enable --py luxwidget


RUN git clone https://github.com/lux-org/lux-logger.git
WORKDIR lux-logger
RUN pip install .
RUN jupyter nbextension install --user logger
RUN jupyter nbextension enable  --user logger/static/main

RUN mkdir src
WORKDIR src/
COPY . .

# Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]

USER root

RUN apt-get update && apt-get install -y postgresql postgresql-client && apt-get clean

#RUN echo "local all all trust" > /etc/postgresql/9.6/main/pg_hba.conf
#RUN echo "host all all ::1/128 trust" >> /etc/postgresql/9.6/main/pg_hba.conf

RUN chown -R postgres:postgres /var/run/postgresql
RUN echo "jovyan ALL=(ALL)   ALL" >> /etc/sudoers
RUN echo "jovyan:redspot" | chpasswd

USER postgres
#Set $NB_USER up with a database.
RUN service postgresql restart \
  && createuser --superuser $NB_USER \
  && createdb $NB_USER $NB_USER


#Check things work, create a test database
USER $NB_USER
#We have to start the postgresql service either as user postgres or as root
RUN echo redspot | sudo -S service postgresql restart \
    && psql $NB_USER -c "CREATE USER test WITH PASSWORD 'testpass';" \
    && createdb -O test test


USER root
COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

USER $NB_USER

COPY *.ipynb ./

# Postgresql python library
RUN pip install --no-cache psycopg2

# SQL support for ipython
RUN pip install --no-cache ipython-sql


ENTRYPOINT ["/entrypoint.sh"]

CMD ["jupyter", "notebook", "--port=8890", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''","--NotebookApp.password=''"]